# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'LBLayoutdemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LBLayoutdemo
pod 'Masonry'
end
